services:
  clickhouse:
    privileged: true
    ports: [8123:8123]
    restart: unless-stopped
    image: clickhouse/clickhouse-server
    volumes:
      - ./.backups:/backups
      - ./.clickhouse/data/:/var/lib/clickhouse/
      - ./.clickhouse/logs/:/var/log/clickhouse-server/
      - ./backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
